name: tools
description: App Description
ignoreFiles: .git node_modules
modules:
- name: puppeteer
  language: nodejs22.x
  web: express
  description: Module description
  prebuildScript: ./install.sh
  functions:
  - name: entry
    entry: entry.js
    description: the entry point for the function